[package]
name = "kvs"
version = "0.1.0"
description = "A key-value store"
edition = "2021"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
